// Generated by tsbindgen - Architecture
// Namespace: express
// Assembly: express

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { Dictionary, IEnumerable, List } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Action, AsyncCallback, Boolean as ClrBoolean, Byte, DateTime, Exception, IAsyncResult, ICloneable, Int32, Int64, IntPtr, MulticastDelegate, Nullable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { ISerializable } from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";

export type CookieEncoder = (value: string) => string;


export type MediaTypeMatcher = (req: Request) => boolean;


export type NextFunction = (control: string) => Task;


export type ParamHandler = (req: Request, res: Response, next: NextFunction, value: unknown, name: string) => Task;


export type QueryParser = (queryString: string) => unknown | undefined;


export type RequestHandler = (req: Request, res: Response, next: NextFunction) => Task;


export type SetHeadersHandler = (res: Response, path: string, stat: FileStat) => void;


export type TemplateEngine = (path: string, options: Dictionary<System_Internal.String, unknown>, callback: Action<Exception, System_Internal.String>) => void;


export type TrustProxyEvaluator = (ip: string) => boolean;


export type VerifyBodyHandler = (req: Request, res: Response, buffer: byte[], encoding: string) => void;


export interface Application$instance extends Router {
    readonly locals: Dictionary<System_Internal.String, unknown | undefined>;
    mountpath: unknown;
    readonly router: Router;
    disable(name: string): Application;
    disabled(name: string): boolean;
    enable(name: string): Application;
    enabled(name: string): boolean;
    engine(ext: string, callback: TemplateEngine): Application;
    get(name: string): unknown | undefined;
    get(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    get(path: unknown, callback: unknown, ...callbacks: unknown[]): unknown;
    listen(path: string, callback?: Action): AppServer;
    listen(port: int, callback?: Action): AppServer;
    listen(port: int, host: string, callback?: Action): AppServer;
    listen(port: int, host: string, backlog: int, callback?: Action): AppServer;
    param(names: string[], callback: ParamHandler): Application;
    param(name: string, callback: ParamHandler): Router;
    param(name: string, callback: ParamHandler): unknown;
    path(): string;
    render(view: string, callback: Action<Exception, System_Internal.String>): void;
    render(view: string, viewLocals: Dictionary<System_Internal.String, unknown>, callback: Action<Exception, System_Internal.String>): void;
    set(name: string, value: unknown): Application;
    use(callback: unknown, ...callbacks: unknown[]): Application;
    use(path: unknown, callback: unknown, ...callbacks: unknown[]): Application;
    use(callback: unknown, ...callbacks: unknown[]): Router;
    use(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    use(callback: unknown, ...callbacks: unknown[]): unknown;
    use(path: unknown, callback: unknown, ...callbacks: unknown[]): unknown;
}


export const Application: {
    new(): Application;
};


export type Application = Application$instance;

export interface AppServer$instance {
    readonly host: string | undefined;
    listening: boolean;
    readonly path: string | undefined;
    readonly port: Nullable<System_Internal.Int32>;
    close(callback?: Action<Exception>): void;
}


export const AppServer: {
    new(port: Nullable<System_Internal.Int32>, host: string, path: string, closeAction: Action): AppServer;
};


export type AppServer = AppServer$instance;

export interface ByteRange$instance {
    end: long;
    start: long;
}


export const ByteRange: {
    new(): ByteRange;
};


export type ByteRange = ByteRange$instance;

export interface CookieOptions$instance {
    get domain(): string | undefined;
    set domain(value: string | undefined);
    get encode(): CookieEncoder | undefined;
    set encode(value: CookieEncoder | undefined);
    expires: Nullable<DateTime>;
    httpOnly: boolean;
    maxAge: Nullable<System_Internal.Int64>;
    partitioned: boolean;
    path: string;
    get priority(): string | undefined;
    set priority(value: string | undefined);
    get sameSite(): unknown | undefined;
    set sameSite(value: unknown | undefined);
    secure: boolean;
    signed: boolean;
}


export const CookieOptions: {
    new(): CookieOptions;
};


export type CookieOptions = CookieOptions$instance;

export interface DownloadOptions$instance {
    acceptRanges: boolean;
    cacheControl: boolean;
    dotfiles: string;
    headers: Dictionary<System_Internal.String, System_Internal.String>;
    immutable: boolean;
    lastModified: boolean;
    maxAge: unknown;
    get root(): string | undefined;
    set root(value: string | undefined);
}


export const DownloadOptions: {
    new(): DownloadOptions;
};


export type DownloadOptions = DownloadOptions$instance;

export interface FileStat$instance {
    modifiedAt: DateTime;
    size: long;
}


export const FileStat: {
    new(): FileStat;
};


export type FileStat = FileStat$instance;

export interface JsonOptions$instance {
    inflate: boolean;
    get limit(): unknown | undefined;
    set limit(value: unknown | undefined);
    get reviver(): unknown | undefined;
    set reviver(value: unknown | undefined);
    strict: boolean;
    get type(): unknown | undefined;
    set type(value: unknown | undefined);
    get verify(): VerifyBodyHandler | undefined;
    set verify(value: VerifyBodyHandler | undefined);
}


export const JsonOptions: {
    new(): JsonOptions;
};


export type JsonOptions = JsonOptions$instance;

export interface RangeOptions$instance {
    combine: boolean;
}


export const RangeOptions: {
    new(): RangeOptions;
};


export type RangeOptions = RangeOptions$instance;

export interface RangeResult$instance {
    readonly ranges: List<ByteRange>;
    type: string;
}


export const RangeResult: {
    new(): RangeResult;
};


export type RangeResult = RangeResult$instance;

export interface RawOptions$instance {
    inflate: boolean;
    get limit(): unknown | undefined;
    set limit(value: unknown | undefined);
    get type(): unknown | undefined;
    set type(value: unknown | undefined);
    get verify(): VerifyBodyHandler | undefined;
    set verify(value: VerifyBodyHandler | undefined);
}


export const RawOptions: {
    new(): RawOptions;
};


export type RawOptions = RawOptions$instance;

export interface Request$instance {
    get app(): Application | undefined;
    set app(value: Application | undefined);
    baseUrl: string;
    get body(): unknown | undefined;
    set body(value: unknown | undefined);
    cookies: Dictionary<System_Internal.String, System_Internal.String>;
    fresh: boolean;
    host: string;
    hostname: string;
    ip: string;
    ips: List<System_Internal.String>;
    method: string;
    originalUrl: string;
    params: Dictionary<System_Internal.String, unknown | undefined>;
    path: string;
    protocol: string;
    query: Dictionary<System_Internal.String, unknown | undefined>;
    get res(): Response | undefined;
    set res(value: Response | undefined);
    get route(): Route | undefined;
    set route(value: Route | undefined);
    readonly secure: boolean;
    signed: boolean;
    signedCookies: Dictionary<System_Internal.String, System_Internal.String>;
    readonly stale: boolean;
    subdomains: List<System_Internal.String>;
    xhr: boolean;
    accepts(...types: string[]): unknown | undefined;
    acceptsCharsets(...charsets: string[]): unknown | undefined;
    acceptsEncodings(...encodings: string[]): unknown | undefined;
    acceptsLanguages(...languages: string[]): unknown;
    get(field: string): string | undefined;
    header(field: string): string | undefined;
    is(...types: string[]): unknown | undefined;
    range(size: long, options?: RangeOptions): unknown;
    setHeader(name: string, value: string): void;
}


export const Request: {
    new(): Request;
};


export type Request = Request$instance;

export interface Response$instance {
    readonly app: Application | undefined;
    headersSent: boolean;
    readonly locals: Dictionary<System_Internal.String, unknown | undefined>;
    get req(): Request | undefined;
    set req(value: Request | undefined);
    statusCode: int;
    append(field: string, value: string): Response;
    append(field: string, values: IEnumerable<System_Internal.String>): Response;
    attachment(filename?: string): Response;
    clearCookie(name: string, options?: CookieOptions): Response;
    contentType(type: string): Response;
    cookie(name: string, value: unknown, options?: CookieOptions): Response;
    download(path: string, filename?: string, options?: DownloadOptions, fn?: Action<Exception>): Response;
    end(data?: unknown, encoding?: string, callback?: Action): Response;
    format(handlers: Dictionary<System_Internal.String, Action>): Response;
    get(field: string): string | undefined;
    header(field: string, value: unknown): Response;
    json(body?: unknown): Response;
    jsonp(body?: unknown): Response;
    links(links: Dictionary<System_Internal.String, System_Internal.String>): Response;
    location(path: string): Response;
    redirect(path: string): Response;
    redirect(status: int, path: string): Response;
    render(view: string): Response;
    render(view: string, viewLocals: Dictionary<System_Internal.String, unknown>): Response;
    render(view: string, callback: Action<Exception, System_Internal.String>): Response;
    render(view: string, viewLocals: Dictionary<System_Internal.String, unknown>, callback: Action<Exception, System_Internal.String>): Response;
    send(body?: unknown): Response;
    sendFile(path: string, options?: SendFileOptions, fn?: Action<Exception>): Response;
    sendStatus(code: int): Response;
    set(field: string, value: unknown): Response;
    set(fields: Dictionary<System_Internal.String, System_Internal.String>): Response;
    status(code: int): Response;
    type(type: string): Response;
    vary(field: string): Response;
}


export const Response: {
    new(): Response;
};


export type Response = Response$instance;

export interface Route$instance extends RoutingHost_1<Route> {
    readonly path: unknown;
    all(callback: unknown, ...callbacks: unknown[]): Route;
    all(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    all(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    checkout(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    checkout(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    copy(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    copy(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    delete(callback: unknown, ...callbacks: unknown[]): Route;
    delete(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    delete(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    get(callback: unknown, ...callbacks: unknown[]): Route;
    get(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    get(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    head(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    head(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    lock_(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    lock_(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    m_search(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    m_search(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    merge(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    merge(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    method(method: string, routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    method(method: string, path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    mkactivity(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    mkactivity(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    mkcol(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    mkcol(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    move(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    move(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    notify(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    notify(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    options(callback: unknown, ...callbacks: unknown[]): Route;
    options(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    options(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    patch(callback: unknown, ...callbacks: unknown[]): Route;
    patch(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    patch(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    post(callback: unknown, ...callbacks: unknown[]): Route;
    post(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    post(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    purge(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    purge(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    put(callback: unknown, ...callbacks: unknown[]): Route;
    put(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    put(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    report(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    report(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    search(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    search(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    subscribe(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    subscribe(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    trace(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    trace(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    unlock(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    unlock(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    unsubscribe(routePath: unknown, callback: unknown, ...callbacks: unknown[]): Route;
    unsubscribe(path: unknown, callback: unknown, ...callbacks: unknown[]): Route;
}


export const Route: {
};


export type Route = Route$instance;

export interface Router$instance extends RoutingHost_1<Router> {
    all(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    all(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    checkout(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    checkout(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    copy(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    copy(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    delete(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    delete(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    get(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    get(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    head(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    head(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    lock_(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    lock_(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    m_search(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    m_search(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    merge(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    merge(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    method(method: string, path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    method(method: string, path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    mkactivity(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    mkactivity(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    mkcol(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    mkcol(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    move(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    move(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    notify(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    notify(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    options(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    options(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    param(name: string, callback: ParamHandler): Router;
    param(name: string, callback: ParamHandler): Router;
    patch(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    patch(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    post(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    post(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    purge(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    purge(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    put(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    put(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    report(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    report(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    route(path: unknown): Route;
    search(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    search(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    subscribe(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    subscribe(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    trace(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    trace(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    unlock(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    unlock(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    unsubscribe(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    unsubscribe(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    use(callback: unknown, ...callbacks: unknown[]): Router;
    use(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
    use(callback: unknown, ...callbacks: unknown[]): Router;
    use(path: unknown, callback: unknown, ...callbacks: unknown[]): Router;
}


export const Router: {
    new(options: RouterOptions): Router;
};


export type Router = Router$instance;

export interface RouterOptions$instance {
    caseSensitive: boolean;
    mergeParams: boolean;
    strict: boolean;
}


export const RouterOptions: {
    new(): RouterOptions;
};


export type RouterOptions = RouterOptions$instance;

export interface RoutingHost_1$instance<TSelf extends RoutingHost_1<TSelf>> {
    all(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    checkout(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    copy(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    delete(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    get(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    head(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    lock_(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    m_search(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    merge(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    method(method: string, path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    mkactivity(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    mkcol(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    move(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    notify(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    options(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    param(name: string, callback: ParamHandler): TSelf;
    patch(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    post(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    purge(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    put(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    report(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    route(path: unknown): Route;
    search(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    subscribe(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    trace(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    unlock(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    unsubscribe(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
    use(callback: unknown, ...callbacks: unknown[]): TSelf;
    use(path: unknown, callback: unknown, ...callbacks: unknown[]): TSelf;
}


export const RoutingHost_1: (abstract new<TSelf extends RoutingHost_1<TSelf>>() => RoutingHost_1<TSelf>) & {
};


export type RoutingHost_1<TSelf extends RoutingHost_1<TSelf>> = RoutingHost_1$instance<TSelf>;

export interface SendFileOptions$instance {
    acceptRanges: boolean;
    cacheControl: boolean;
    dotfiles: string;
    headers: Dictionary<System_Internal.String, System_Internal.String>;
    immutable: boolean;
    lastModified: boolean;
    maxAge: unknown;
    get root(): string | undefined;
    set root(value: string | undefined);
}


export const SendFileOptions: {
    new(): SendFileOptions;
};


export type SendFileOptions = SendFileOptions$instance;

export interface StaticOptions$instance {
    acceptRanges: boolean;
    cacheControl: boolean;
    dotfiles: string;
    etag: boolean;
    get extensions(): unknown | undefined;
    set extensions(value: unknown | undefined);
    fallthrough: boolean;
    immutable: boolean;
    get index(): unknown | undefined;
    set index(value: unknown | undefined);
    lastModified: boolean;
    maxAge: unknown;
    redirect: boolean;
    get setHeaders(): SetHeadersHandler | undefined;
    set setHeaders(value: SetHeadersHandler | undefined);
}


export const StaticOptions: {
    new(): StaticOptions;
};


export type StaticOptions = StaticOptions$instance;

export interface TextOptions$instance {
    defaultCharset: string;
    inflate: boolean;
    get limit(): unknown | undefined;
    set limit(value: unknown | undefined);
    get type(): unknown | undefined;
    set type(value: unknown | undefined);
    get verify(): VerifyBodyHandler | undefined;
    set verify(value: VerifyBodyHandler | undefined);
}


export const TextOptions: {
    new(): TextOptions;
};


export type TextOptions = TextOptions$instance;

export interface UrlEncodedOptions$instance {
    depth: int;
    extended: boolean;
    inflate: boolean;
    get limit(): unknown | undefined;
    set limit(value: unknown | undefined);
    parameterLimit: int;
    get type(): unknown | undefined;
    set type(value: unknown | undefined);
    get verify(): VerifyBodyHandler | undefined;
    set verify(value: VerifyBodyHandler | undefined);
}


export const UrlEncodedOptions: {
    new(): UrlEncodedOptions;
};


export type UrlEncodedOptions = UrlEncodedOptions$instance;

export abstract class express$instance {
    static app(): Application;
    static application(): Application;
    static create(): Application;
    static json(options?: JsonOptions): RequestHandler;
    static raw(options?: RawOptions): RequestHandler;
    static Router(options?: RouterOptions): Router;
    static static(root: string, options?: StaticOptions): RequestHandler;
    static text(options?: TextOptions): RequestHandler;
    static urlencoded(options?: UrlEncodedOptions): RequestHandler;
}


export type express = express$instance;

