// Generated by tsbindgen - Architecture
// Namespace: express
// Assembly: express

// Import types from other namespaces

export type CookieEncoder = (value: string) => string;


export type ErrorRequestHandler = (err: Error, req: Request, res: Response, next: NextFunction) => Promise<void>;


export type MediaTypeMatcher = (req: Request) => boolean;


export type NextFunction = (control?: string) => Promise<void>;


export type ParamHandler = (req: Request, res: Response, next: NextFunction, value: unknown, name: string) => Promise<void>;


export type QueryParser = (queryString: string) => unknown | undefined;


export type RequestHandler = (req: Request, res: Response, next: NextFunction) => Promise<void>;


export type SetHeadersHandler = (res: Response, path: string, stat: FileStat) => void;


export type TemplateEngine = (path: string, options: Record<string, unknown>, callback: (err: Error | undefined, html: string | undefined) => void) => void;


export type TrustProxyEvaluator = (ip: string) => boolean;


export type VerifyBodyHandler = (req: Request, res: Response, buffer: Uint8Array, encoding: string) => void;


export interface Application$instance extends Router {
    readonly __tsonic_type_express_Application: never;

    readonly locals: Record<string, unknown | undefined>;
    mountpath: string | string[];
    readonly router: Router;
    disable(name: string): Application;
    disabled(name: string): boolean;
    enable(name: string): Application;
    enabled(name: string): boolean;
    engine(ext: string, callback: TemplateEngine): Application;
    get(name: string): unknown | undefined;
    get(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): Router;
    listen(path: string, callback?: () => void): AppServer;
    listen(port: number, callback?: () => void): AppServer;
    listen(port: number, host: string, callback?: () => void): AppServer;
    listen(port: number, host: string, backlog: number, callback?: () => void): AppServer;
    param(names: string[], callback: ParamHandler): Application;
    param(name: string, callback: ParamHandler): Router;
    path(): string;
    render(view: string, callback: (err: Error | undefined, html: string | undefined) => void): void;
    render(view: string, viewLocals: Record<string, unknown>, callback: (err: Error | undefined, html: string | undefined) => void): void;
    set(name: string, value: unknown): Application;
}


export const Application: {
    new(): Application;
};


export type Application = Application$instance;

export interface AppServer$instance {
    readonly __tsonic_type_express_AppServer: never;

    readonly host: string | undefined;
    listening: boolean;
    readonly path: string | undefined;
    readonly port: number | undefined;
    close(callback?: (err: Error | undefined) => void): void;
}


export const AppServer: {
};


export type AppServer = AppServer$instance;

export interface ByteRange$instance {
    readonly __tsonic_type_express_ByteRange: never;

    end: number;
    start: number;
}


export const ByteRange: {
    new(): ByteRange;
};


export type ByteRange = ByteRange$instance;

export interface CookieOptions {
    domain?: string;
    encode?: CookieEncoder;
    expires?: Date;
    httpOnly?: boolean;
    maxAge?: number;
    partitioned?: boolean;
    path?: string;
    priority?: string;
    sameSite?: string | boolean;
    secure?: boolean;
    signed?: boolean;
}


export const CookieOptions: {
    new(): CookieOptions;
};

export interface Cookies$instance {
    readonly __tsonic_type_express_Cookies: never;

}


export const Cookies: {
    new(): Cookies;
};


export type Cookies = Cookies$instance & { readonly [key: string]: string | undefined; };

export interface CorsOptions {
    allowedHeaders?: string[];
    credentials?: boolean;
    exposedHeaders?: string[];
    maxAgeSeconds?: number;
    methods?: string[];
    optionsSuccessStatus?: number;
    origins?: string[];
    preflightContinue?: boolean;
}


export const CorsOptions: {
    new(): CorsOptions;
};

export interface DownloadOptions {
    acceptRanges?: boolean;
    cacheControl?: boolean;
    dotfiles?: string;
    headers?: Record<string, string>;
    immutable?: boolean;
    lastModified?: boolean;
    maxAge?: string | number;
    root?: string;
}


export const DownloadOptions: {
    new(): DownloadOptions;
};

export interface Files$instance {
    readonly __tsonic_type_express_Files: never;

}


export const Files: {
    new(): Files;
};


export type Files = Files$instance & { readonly [field: string]: UploadedFile[] | undefined; };

export interface FileStat$instance {
    readonly __tsonic_type_express_FileStat: never;

    modifiedAt: Date;
    size: number;
}


export const FileStat: {
    new(): FileStat;
};


export type FileStat = FileStat$instance;

export interface JsonOptions {
    inflate?: boolean;
    limit?: string | number;
    reviver?: unknown;
    strict?: boolean;
    type?: string | string[] | MediaTypeMatcher;
    verify?: VerifyBodyHandler;
}


export const JsonOptions: {
    new(): JsonOptions;
};

export interface Multipart$instance {
    readonly __tsonic_type_express_Multipart: never;

    any(): RequestHandler;
    array(name: string, maxCount?: number | undefined): RequestHandler;
    fields(fields: MultipartField[]): RequestHandler;
    none(): RequestHandler;
    single(name: string): RequestHandler;
}


export const Multipart: {
    new(options: MultipartOptions): Multipart;
};


export type Multipart = Multipart$instance;

export interface MultipartField {
    maxCount?: number;
    name: string;
}


export const MultipartField: {
    new(): MultipartField;
};

export interface MultipartOptions {
    maxFileCount?: number;
    maxFileSizeBytes?: number;
    type?: string;
}


export const MultipartOptions: {
    new(): MultipartOptions;
};

export interface Params$instance {
    readonly __tsonic_type_express_Params: never;

}


export const Params: {
    new(): Params;
};


export type Params = Params$instance & { readonly [key: string]: string | undefined; };

export interface RangeOptions {
    combine?: boolean;
}


export const RangeOptions: {
    new(): RangeOptions;
};

export interface RangeResult$instance {
    readonly __tsonic_type_express_RangeResult: never;

    ranges: ByteRange[];
    type: string;
}


export const RangeResult: {
    new(): RangeResult;
};


export type RangeResult = RangeResult$instance;

export interface RawOptions {
    inflate?: boolean;
    limit?: string | number;
    type?: string | string[] | MediaTypeMatcher;
    verify?: VerifyBodyHandler;
}


export const RawOptions: {
    new(): RawOptions;
};

export interface Request$instance {
    readonly __tsonic_type_express_Request: never;

    get app(): Application | undefined;
    set app(value: Application | undefined);
    baseUrl: string;
    get body(): unknown | undefined;
    set body(value: unknown | undefined);
    readonly cookies: Cookies;
    get file(): UploadedFile | undefined;
    set file(value: UploadedFile | undefined);
    readonly files: Files;
    fresh: boolean;
    host: string;
    hostname: string;
    ip: string;
    ips: string[];
    method: string;
    originalUrl: string;
    readonly params: Params;
    path: string;
    protocol: string;
    query: Record<string, unknown | undefined>;
    get res(): Response | undefined;
    set res(value: Response | undefined);
    get route(): Route | undefined;
    set route(value: Route | undefined);
    readonly secure: boolean;
    signed: boolean;
    readonly signedCookies: Cookies;
    readonly stale: boolean;
    subdomains: string[];
    xhr: boolean;
    accepts(...types: string[]): string | false;
    acceptsCharsets(...charsets: string[]): string | false;
    acceptsEncodings(...encodings: string[]): string | false;
    acceptsLanguages(...languages: string[]): string | string[] | false;
    get(field: string): string | undefined;
    header(field: string): string | undefined;
    is(...types: string[]): string | false | undefined;
    param(name: string): string | undefined;
    range(size: number, options?: RangeOptions): RangeResult | -1;
    setHeader(name: string, value: string): void;
}


export const Request: {
    new(): Request;
};


export type Request = Request$instance;

export interface Response$instance {
    readonly __tsonic_type_express_Response: never;

    readonly app: Application | undefined;
    headersSent: boolean;
    readonly locals: Record<string, unknown | undefined>;
    get req(): Request | undefined;
    set req(value: Request | undefined);
    statusCode: number;
    append(field: string, value: string): Response;
    append(field: string, values: readonly string[]): Response;
    attachment(filename?: string): Response;
    clearCookie(name: string, options?: CookieOptions): Response;
    contentType(type: string): Response;
    cookie(name: string, value: unknown, options?: CookieOptions): Response;
    download(path: string, filename?: string, options?: DownloadOptions, fn?: (err: Error | undefined) => void): Response;
    end(data?: unknown, encoding?: string, callback?: () => void): Response;
    format(handlers: Record<string, () => void>): Response;
    get(field: string): string | undefined;
    header(field: string, value: unknown): Response;
    json(body?: unknown): Response;
    jsonp(body?: unknown): Response;
    links(links: Record<string, string>): Response;
    location(path: string): Response;
    redirect(path: string): Response;
    redirect(status: number, path: string): Response;
    render(view: string): Response;
    render(view: string, viewLocals: Record<string, unknown>): Response;
    render(view: string, callback: (err: Error | undefined, html: string | undefined) => void): Response;
    render(view: string, viewLocals: Record<string, unknown>, callback: (err: Error | undefined, html: string | undefined) => void): Response;
    send(body?: unknown): Response;
    sendFile(path: string, options?: SendFileOptions, fn?: (err: Error | undefined) => void): Response;
    sendStatus(code: number): Response;
    set(field: string, value: unknown): Response;
    set(fields: Record<string, string>): Response;
    status(code: number): Response;
    type(type: string): Response;
    vary(field: string): Response;
}


export const Response: {
    new(): Response;
};


export type Response = Response$instance;

export interface Route$instance extends RoutingHost_1<Route> {
    readonly __tsonic_type_express_Route: never;

    readonly path: unknown;
    all(callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    all(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    delete(callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    delete(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    get(callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    get(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    options(callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    options(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    patch(callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    patch(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    post(callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    post(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    put(callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
    put(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): Route;
}


export const Route: {
};


export type Route = Route$instance;

export interface Router$instance extends RoutingHost_1<Router> {
    readonly __tsonic_type_express_Router: never;

    param(name: string, callback: ParamHandler): Router;
    use(callback: Router): Router;
    use(callback: RequestHandler, ...callbacks: RequestHandler[]): Router;
    use(path: string, callback: Router): Router;
    use(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): Router;
}


export const Router: {
    new(options: RouterOptions): Router;
};


export type Router = Router$instance;

export interface RouterOptions {
    caseSensitive?: boolean;
    mergeParams?: boolean;
    strict?: boolean;
}


export const RouterOptions: {
    new(): RouterOptions;
};

export interface RoutingHost_1$instance<TSelf extends RoutingHost_1<TSelf>> {
    readonly __tsonic_type_express_RoutingHost_1: never;

    all(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    checkout(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    copy(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    delete(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    get(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    head(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    lock_(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    m_search(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    merge(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    method(method: string, path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    mkactivity(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    mkcol(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    move(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    notify(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    options(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    param(name: string, callback: ParamHandler): TSelf;
    patch(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    post(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    purge(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    put(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    report(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    route(path: string): Route;
    search(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    subscribe(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    trace(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    unlock(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    unsubscribe(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    use(callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    use(path: string, callback: RequestHandler, ...callbacks: RequestHandler[]): TSelf;
    useError(callback: ErrorRequestHandler, ...callbacks: ErrorRequestHandler[]): TSelf;
    useError(path: string, callback: ErrorRequestHandler, ...callbacks: ErrorRequestHandler[]): TSelf;
}


export const RoutingHost_1: (abstract new<TSelf extends RoutingHost_1<TSelf>>() => RoutingHost_1<TSelf>) & {
};


export type RoutingHost_1<TSelf extends RoutingHost_1<TSelf>> = RoutingHost_1$instance<TSelf>;

export interface SendFileOptions {
    acceptRanges?: boolean;
    cacheControl?: boolean;
    dotfiles?: string;
    headers?: Record<string, string>;
    immutable?: boolean;
    lastModified?: boolean;
    maxAge?: string | number;
    root?: string;
}


export const SendFileOptions: {
    new(): SendFileOptions;
};

export interface StaticOptions {
    acceptRanges?: boolean;
    cacheControl?: boolean;
    dotfiles?: string;
    etag?: boolean;
    extensions?: string[] | false;
    fallthrough?: boolean;
    immutable?: boolean;
    index?: string | string[] | false;
    lastModified?: boolean;
    maxAge?: string | number;
    redirect?: boolean;
    setHeaders?: SetHeadersHandler;
}


export const StaticOptions: {
    new(): StaticOptions;
};

export interface TextOptions {
    defaultCharset?: string;
    inflate?: boolean;
    limit?: string | number;
    type?: string | string[] | MediaTypeMatcher;
    verify?: VerifyBodyHandler;
}


export const TextOptions: {
    new(): TextOptions;
};

export interface UploadedFile$instance {
    readonly __tsonic_type_express_UploadedFile: never;

    readonly fieldname: string;
    readonly mimetype: string;
    readonly originalname: string;
    readonly size: number;
    bytes(): Promise<Uint8Array>;
    save(path: string): Promise<void>;
    text(): Promise<string>;
}


export const UploadedFile: {
};


export type UploadedFile = UploadedFile$instance;

export interface UrlEncodedOptions {
    depth?: number;
    extended?: boolean;
    inflate?: boolean;
    limit?: string | number;
    parameterLimit?: number;
    type?: string | string[] | MediaTypeMatcher;
    verify?: VerifyBodyHandler;
}


export const UrlEncodedOptions: {
    new(): UrlEncodedOptions;
};

export abstract class express$instance {
    static app(): Application;
    static application(): Application;
    static cookieParser(secret: string): RequestHandler;
    static cors(options?: CorsOptions): RequestHandler;
    static create(): Application;
    static json(options?: JsonOptions): RequestHandler;
    static multipart(options?: MultipartOptions): Multipart;
    static raw(options?: RawOptions): RequestHandler;
    static Router(options?: RouterOptions): Router;
    static static(root: string, options?: StaticOptions): RequestHandler;
    static text(options?: TextOptions): RequestHandler;
    static urlencoded(options?: UrlEncodedOptions): RequestHandler;
}


export type express = express$instance;

